
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


CREATE TABLE `admin` (
  `id` int(11) NOT NULL,
  `UserName` varchar(100) DEFAULT NULL,
  `Password` varchar(100) DEFAULT NULL,
  `updationDate` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;



INSERT INTO `admin` (`id`, `UserName`, `Password`, `updationDate`) VALUES
(1, 'admin','202cb962ac59075b964b07152d234b70', '2024-04-24 05:48:49');

CREATE TABLE `booking` (
  `BookingId` int(11) NOT NULL,
  `PackageId` int(11) DEFAULT NULL,
  `FirstName` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `Email` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `Phone` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `NameOnCard` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `CardNumber` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `ExpMonth` varchar(11) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `ExpYear` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `CVV` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `Country` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `StreetLine1` varchar(200) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `StreetLine2` varchar(200) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `City` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `State1` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `Pincode` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `Additional_Information` varchar(200) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `CancelledBy` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `BookingTime` timestamp NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



INSERT INTO `booking` (`BookingId`, `PackageId`, `FirstName`, `Email`, `Phone`, `NameOnCard`, `CardNumber`, `ExpMonth`, `ExpYear`, `CVV`, `Country`, `StreetLine1`, `StreetLine2`, `City`, `State1`, `Pincode`, `Additional_Information`, `status`, `CancelledBy`, `BookingTime`) VALUES
(38, 18, 'Pratik Sarvaiya', 'pratik@gmail.com', '09998704534', 'Harsh', '1234567891234567', '11', '2025', '', 'India', 'Jhalwa', '', 'Prayagraj', 'Uttar Pradesh', '211015', 'samosa', 0, NULL, '2024-04-23 07:29:13'),
(40, 18, 'Harsh', 'harsh@gmail.com', '8160112345', 'Harsh', '1234567891234567', '11', '2025', '', 'India', 'Jhalwa', 'pray', 'Prayagraj', 'Uttarpradesh', '211015', 'pls chal ja', 0, NULL, '2024-04-23 07:39:50'),
(41, 25, 'Harsh', 'harsh@gmail.com', '8160112345', 'Harsh', '1234567891234567', '11', '2025', '', 'India', 'Jhalwa', 'pray', 'Prayagraj', 'Uttarpradsh', '211015', 'add', 2, 'a', '2024-04-23 07:41:31');



CREATE TABLE `packageoffer` (
  `OfferId` int(11) NOT NULL,
  `OfferName` varchar(200) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `OfferLocation` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `OfferDetails` mediumtext CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `ActualPrice` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `OfferPrice` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `PercentageOff` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `OfferImage` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `Creationdate` timestamp NULL DEFAULT current_timestamp(),
  `UpdationDate` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



INSERT INTO `packageoffer` (`OfferId`, `OfferName`, `OfferLocation`, `OfferDetails`, `ActualPrice`, `OfferPrice`, `PercentageOff`, `OfferImage`, `Creationdate`, `UpdationDate`) VALUES
(10, 'Darjeeling-Town in West Bengal', 'West Bengal', 'The following day, we got up late, but it was still dark outside. An irritating faint knocking sound on the window did wake me. I reluctantly moved the curtains and what I saw outside made me rub my eyes. It’s snowing! The snowflakes were knocking against the glass panes. With uncontrollable excitement, we decided the venture to Chowrasta. Foggy weather conditions and low visibility forced most people to stay indoors, barring a few excited tourists like us from the plains who flocked the hills to witness the snowfall. The temperature was 3°C and, thankfully, was not windy. We did experience snowfall earlier, but it was a lifetime experience for kids – their first snowfall. I was awestruck to see that still there is a long queue out Kev’s for breakfast. Adverse weather did not allow us to stay out for long; we had to come back after spending a couple of hours. The rest of the day was lazing on the couch, watching online streaming and enjoying our favourite poison. We had Darjeeling offbeat locations travel plans the following days. But not sure about the feasibility in the present climatic conditions. The alarm goes off. What torture during holidays! The room is freezing outside the electric blanket. Saw the first glimpse of sunlight on the peak. An SMS flashing on the screen “Sir Ji, weather is clear. Be ready at 8.30”. I was about to ignore the alarm, then suddenly remembered our driver would honk in the next 90 minutes. Better wake up, make the kids ready and all set to a great day ahead. Around 9 am, after completing our banana pancake in breakfast, it is time we hit the road. Excited to think of the memories we are going to make today. Lepchajagat is 18 km from Darjeeling, at an altitude of 6959 feet. As the name suggests, the place was once predominantly a settlement by the Lepcha tribe. Today the tiny hamlet is significantly a reserve forest area filled with thick oak, firs and rhododendron trees. The offbeat forest is 45 minutes driving from Darjeeling.', '6550', '5900', '15%', '6467143468923.jpg', '2023-05-19 06:16:20', NULL),
(11, 'Ladakh, Jammu and Kashmir', 'Jammu and Kashmir', 'Ladakh, union territory of India, located in the northern part of the Indian subcontinent in the vicinity of the Karakoram and westernmost Himalayan mountain ranges. It is bounded by Jammu and Kashmir union territory to the west and by Himachal Pradesh to the south; its northern and eastern borders are disputed with Pakistan and China, respectively. Ladakh was administered as part of Jammu and Kashmir state from 1947 until 2019, when it became a separate administrative unit. Area 22,836 square miles (59,146 square km). Pop. (2011) 274,289. Geologically complex and topographically immense, the Great Himalayas contain ranges with numerous peaks reaching elevations of 20,000 feet (6,100 metres) or higher, between which lie deeply entrenched remote valleys. Running parallel to the main Great Himalayas directly to the east is the Zaskar Range, which begins its flank from the main range at the Karnali River to the southeast of Ladakh. The zone was heavily glaciated during the Pleistocene Epoch, and remnant glaciers and snowfields are still present. The mountains constitute a climatic divide, representing a transition from the monsoon climate of the Indian subcontinent in neighbouring Jammu and Kashmir to the dry continental climate of Central Asia and Tibet. The valley of the upper Indus River is a well-defined feature that follows the geologic strike (structural trend) westward from the Tibetan border to the point in the Pakistani sector of Kashmir where the river rounds the great mountainous mass of Nanga Parbat to run southward in deep gorges that cut across the strike. In its upper reaches the river is flanked by gravel terraces; each tributary builds an alluvial fan out into the main valley. The town of Leh stands on such a fan, 11,500 feet (3,500 metres) above sea level, with a climate characterized by an almost total lack of precipitation, by intense insolation (exposure to sunlight), and by great diurnal and annual ranges in temperature. Life depends on meltwater from the surrounding mountains, and vegetation is alpine (i.e., consists of species above the tree line), growing on thin soils.', '8999', '7600', '20%', '64671589e4748.jpg', '2023-05-19 06:22:01', NULL),
(12, 'Mysuru-City in Karnataka', 'Karnataka', 'Mysuru, also called Mysore, city, south-central Karnataka state, southern India. It lies northwest of Chamundi Hill and midway between the Kaveri (Cauvery) and Kabani (Kabbani) rivers on the undulating Deccan plateau at an elevation of 2,525 feet (770 metres). The land surrounding the city is characterized by rain-filled shallow depressions (tanks). The site was mentioned in the epic Mahabharata as Mahishmati (Mahismati). Mysore was known as Purigere in the Mauryan era (3rd century BCE) and later became Mahishapura. It was the administrative capital of the princely state of Mysore from 1799 to 1831 and long was the second most-populous city (after Bengaluru [Bangalore]) of Karnataka state, until being surpassed by Hubballi-Dharwad in the second half of the 20th century. Its urban agglomeration, however, is still the state’s second largest. Mysuru is an important manufacturing and trading centre, and it has textile (cotton and silk), rice, and oil mills, sandalwood-oil and chemical factories, and tanneries. The suburb of Belagula, to the northwest, produces chrome dyes and chemical fertilizer. The city’s industries are powered by the hydroelectric station near Sivasamudram Island to the east. Mysuru’s cottage industries include cotton weaving, tobacco and coffee processing, and the making of bidis (cigarettes). The area is known for its artwork in ivory, metal, and wood, and the market near the railway station serves as a collection centre for local farm products. The city has an airport, lies at the junction of two northern railway lines, and is a major intersection on India’s principal western road system. An ancient fort, rebuilt along European lines in the 18th century, stands in the centre of Mysuru. The fort area comprises Mysore Palace (1912) with its ivory and gold throne, Curzon Park, the Silver Jubilee Clock Tower (1927), Gandhi Square, and two statues of maharajas. To the west, near Gordon Park, are the former British residency (1805), the noted Oriental Library, university buildings, and public offices. Jaganmohan Palace and Lalitha Mahal are other notable buildings. The University of Mysore was founded in 1916; other educational facilities include Maharaja’s College, Maharani’s College for Women, and affiliated colleges of medicine, law, engineering, and teacher training. There are also several institutions for the advancement of Kannada culture.', '7699', '7300', '10%', '6467163cdec85.jpg', '2023-05-19 06:25:00', NULL),
(13, 'Mata Vaishno Devi Temple', 'Katra-Jammu and Kashmir', 'The second-most visited Hindu pilgrimage destination in India, Mata Vaishno Devi Cave Temple is situated in the Trikuta Hills in Katra, Jammu & Kashmir. Hindu devotees from all over the world visit this famed religious site where the Mother Goddess or Mata Vaishno Devi is said to fulfill their wishes. This religious place is considered the most important Shaktipeeth as it is believed, here the skull of the Goddess Sati fell. At Mata Vaishno Devi Cave, the goddess is in the form of a five and a half feet tall rock which has three heads or the Pindies. On Mata Vaishno Devi pilgrimage, devotees make traditional offerings to Mata of chunri (a red coloured drape), sarees, dry fruits, silver or gold ornaments, cholas, flowers etc. Mata Vaishno Devi Shrine Board was formedu in 1986 and ever since this most popular religious site in Jammu started to attract a lot of Hindu pilgrims. The holy cave of Mata Vaishno Devi is said to have been discovered by Pandit Sridhar, a Hindu priest. Goddess Vaishnavi appeared in the dream of the priest and instructed him on how to find here abode on Trikuta Hills. The priest following her instruction heads out for the journey after the dream and found the cave as instructed earlier. Mata Vaishno Devi appeared to him and blessed him with four sons. She also gave him the boon of being the custodian of the cave. Even today, Pandit Shridhar’s descendant abide by the commitment.', '8599', '6300', '30%', '646716a17ddc8.jpg', '2023-05-19 06:26:41', NULL);



CREATE TABLE `tbldestination` (
  `DestinationId` int(11) NOT NULL,
  `DestinationName` varchar(200) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `DestinationLocation` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `DestinationDetails` mediumtext CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `DestinationImage` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `Creationdate` timestamp NULL DEFAULT current_timestamp(),
  `UpdationDate` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



INSERT INTO `tbldestination` (`DestinationId`, `DestinationName`, `DestinationLocation`, `DestinationDetails`, `DestinationImage`, `Creationdate`, `UpdationDate`) VALUES
(13, 'Taj Mahal-An immense mausoleum', 'Agra-Uttar Pradesh', 'The Taj Mahal is located on the right bank of the Yamuna River in a vast Mughal garden that encompasses nearly 17 hectares, in the Agra District in Uttar Pradesh. It was built by Mughal Emperor Shah Jahan in memory of his wife Mumtaz Mahal with construction starting in 1632 AD and completed in 1648 AD, with the mosque, the guest house and the main gateway on the south, the outer courtyard and its cloisters were added subsequently and completed in 1653 AD. The existence of several historical and Quaranic inscriptions in Arabic script have facilitated setting the chronology of Taj Mahal. For its construction, masons, stone-cutters, inlayers, carvers, painters, calligraphers, dome builders and other artisans were requisitioned from the whole of the empire and also from the Central Asia and Iran. Ustad-Ahmad Lahori was the main architect of the Taj Mahal.\r\n\r\nThe Taj Mahal is considered to be the greatest architectural achievement in the whole range of Indo-Islamic architecture. Its recognised architectonic beauty has a rhythmic combination of solids and voids, concave and convex and light shadow; such as arches and domes further increases the aesthetic aspect. The colour combination of lush green scape reddish pathway and blue sky over it show cases the monument in ever changing tints and moods. The relief work in marble and inlay with precious and semi precious stones make it a monument apart. \r\nThe four free-standing minarets at the corners of the platform added a hitherto unknown dimension to the Mughal architecture. The four minarets provide not only a kind of spatial reference to the monument but also give a three dimensional effect to the edifice.\r\n\r\nThe most impressive in the Taj Mahal complex next to the tomb, is the main gate which stands majestically in the centre of the southern wall of the forecourt. The gate is flanked on the north front by double arcade galleries. The garden in front of the galleries is subdivided into four quarters by two main walk-ways and each quarters in turn subdivided by the narrower cross-axial walkways, on the Timurid-Persian scheme of the walled in garden. The enclosure walls on the east and west have a pavilion at the centre.', '6466ff8b68299.jpg', '2023-05-19 05:43:31', '2024-04-23 18:21:11'),
(14, 'Darjeeling-Town in West Bengal', 'West Bengal', 'The following day, we got up late, but it was still dark outside. An irritating faint knocking sound on the window did wake me. I reluctantly moved the curtains and what I saw outside made me rub my eyes. It’s snowing! The snowflakes were knocking against the glass panes. With uncontrollable excitement, we decided the venture to Chowrasta. Foggy weather conditions and low visibility forced most people to stay indoors, barring a few excited tourists like us from the plains who flocked the hills to witness the snowfall. The temperature was 3°C and, thankfully, was not windy. We did experience snowfall earlier, but it was a lifetime experience for kids – their first snowfall. I was awestruck to see that still there is a long queue out Kev’s for breakfast. Adverse weather did not allow us to stay out for long; we had to come back after spending a couple of hours. The rest of the day was lazing on the couch, watching online streaming and enjoying our favourite poison. We had Darjeeling offbeat locations travel plans the following days. But not sure about the feasibility in the present climatic conditions. The alarm goes off. What torture during holidays! The room is freezing outside the electric blanket. Saw the first glimpse of sunlight on the peak. An SMS flashing on the screen “Sir Ji, weather is clear. Be ready at 8.30”. I was about to ignore the alarm, then suddenly remembered our driver would honk in the next 90 minutes. Better wake up, make the kids ready and all set to a great day ahead. Around 9 am, after completing our banana pancake in breakfast, it is time we hit the road. Excited to think of the memories we are going to make today. Lepchajagat is 18 km from Darjeeling, at an altitude of 6959 feet. As the name suggests, the place was once predominantly a settlement by the Lepcha tribe. Today the tiny hamlet is significantly a reserve forest area filled with thick oak, firs and rhododendron trees. The offbeat forest is 45 minutes driving from Darjeeling.', '6467143468923.jpg', '2023-05-19 05:47:40', NULL),
(15, 'Ladakh, Jammu and Kashmir', 'Jammu and Kashmir', 'Ladakh, union territory of India, located in the northern part of the Indian subcontinent in the vicinity of the Karakoram and westernmost Himalayan mountain ranges. It is bounded by Jammu and Kashmir union territory to the west and by Himachal Pradesh to the south; its northern and eastern borders are disputed with Pakistan and China, respectively. Ladakh was administered as part of Jammu and Kashmir state from 1947 until 2019, when it became a separate administrative unit. Area 22,836 square miles (59,146 square km). Pop. (2011) 274,289.\r\nGeologically complex and topographically immense, the Great Himalayas contain ranges with numerous peaks reaching elevations of 20,000 feet (6,100 metres) or higher, between which lie deeply entrenched remote valleys. Running parallel to the main Great Himalayas directly to the east is the Zaskar Range, which begins its flank from the main range at the Karnali River to the southeast of Ladakh. The zone was heavily glaciated during the Pleistocene Epoch, and remnant glaciers and snowfields are still present. The mountains constitute a climatic divide, representing a transition from the monsoon climate of the Indian subcontinent in neighbouring Jammu and Kashmir to the dry continental climate of Central Asia and Tibet.\r\nThe valley of the upper Indus River is a well-defined feature that follows the geologic strike (structural trend) westward from the Tibetan border to the point in the Pakistani sector of Kashmir where the river rounds the great mountainous mass of Nanga Parbat to run southward in deep gorges that cut across the strike. In its upper reaches the river is flanked by gravel terraces; each tributary builds an alluvial fan out into the main valley. The town of Leh stands on such a fan, 11,500 feet (3,500 metres) above sea level, with a climate characterized by an almost total lack of precipitation, by intense insolation (exposure to sunlight), and by great diurnal and annual ranges in temperature. Life depends on meltwater from the surrounding mountains, and vegetation is alpine (i.e., consists of species above the tree line), growing on thin soils.', '6467077b0c75d.jpg', '2023-05-19 05:50:55', NULL),
(16, 'Mysuru-City in Karnataka', 'Karnataka', 'Mysuru, also called Mysore, city, south-central Karnataka state, southern India. It lies northwest of Chamundi Hill and midway between the Kaveri (Cauvery) and Kabani (Kabbani) rivers on the undulating Deccan plateau at an elevation of 2,525 feet (770 metres). The land surrounding the city is characterized by rain-filled shallow depressions (tanks).\r\n\r\nThe site was mentioned in the epic Mahabharata as Mahishmati (Mahismati). Mysore was known as Purigere in the Mauryan era (3rd century BCE) and later became Mahishapura. It was the administrative capital of the princely state of Mysore from 1799 to 1831 and long was the second most-populous city (after Bengaluru [Bangalore]) of Karnataka state, until being surpassed by Hubballi-Dharwad in the second half of the 20th century. Its urban agglomeration, however, is still the state’s second largest.\r\n\r\nMysuru is an important manufacturing and trading centre, and it has textile (cotton and silk), rice, and oil mills, sandalwood-oil and chemical factories, and tanneries. The suburb of Belagula, to the northwest, produces chrome dyes and chemical fertilizer. The city’s industries are powered by the hydroelectric station near Sivasamudram Island to the east. Mysuru’s cottage industries include cotton weaving, tobacco and coffee processing, and the making of bidis (cigarettes). The area is known for its artwork in ivory, metal, and wood, and the market near the railway station serves as a collection centre for local farm products. The city has an airport, lies at the junction of two northern railway lines, and is a major intersection on India’s principal western road system.\r\nAn ancient fort, rebuilt along European lines in the 18th century, stands in the centre of Mysuru. The fort area comprises Mysore Palace (1912) with its ivory and gold throne, Curzon Park, the Silver Jubilee Clock Tower (1927), Gandhi Square, and two statues of maharajas. To the west, near Gordon Park, are the former British residency (1805), the noted Oriental Library, university buildings, and public offices. Jaganmohan Palace and Lalitha Mahal are other notable buildings. The University of Mysore was founded in 1916; other educational facilities include Maharaja’s College, Maharani’s College for Women, and affiliated colleges of medicine, law, engineering, and teacher training. There are also several institutions for the advancement of Kannada culture.', '6467097f8c7b1.jpg', '2023-05-19 05:59:47', NULL),
(17, 'Kedarnath Town in Uttarakhand', 'Uttarakhand', 'Kedarnath is one of the most sacred pilgrimages of Lord Shiva situated in Rudraprayag district of Garhwal region in Uttarakhand. Kedarnath is one of the Char Dham in Uttarakhand and the most important dham among Panch kedar. Kedarnath is situated at an altitude of 3586 mts, in the lap of the majestic mountain peaks and near the head of river Mandakini, Kedarnath range stands one of the twelve Jyotirlingas of Lord Shiva.\\r\\n\\r\\nKedar meaning powerful is another name of Lord Shiva the protector and the destroyer. The beautiful ambiance around the temple looks like quite peace on heaven causes a beautiful place to do meditation.The main attractions here is the Shiva Temple, which is a popular Hindu shrine and pilgrimage, attracting devotees from all over the world. The travel and tourism scope here is strengthened by factors like natural beauty and religious zest.\\r\\n\\r\\nShiva is considered the embodiment of all passions - love, hatred, fear, death and mysticism which are expressed through his various forms. There are more than 200 shrines dedicated to Lord Shiva in the area itself, the most important one is Kedarnath.\\r\\nKedarnath Temple is the most revered shrine of Hindu deity Lord Shiva. The Mandir was built in 8th century A.D. by Adi Shankaracharya. It is adjacent to the site of an earlier temple built by the Pandavas. Kedarnath is one of India’s most famous temples (more than 1000 years old temple) dedicated to Lord Shiva.\\r\\n\\r\\nKedarnath Temple complex is being rehabilitated after 2013 Kedarnath floods. New facilities include helipads, helipad and new guest houses. Online facilities for Kedarnath booking are also there. Kedarnath Puja can be book online and no physical presence of devotees needed. Some pujas could be book on the internet or in person. The daily pooja rituals at the Kedarnath temple start early morning, around 4.00 am with Maha Abhishek and end at around 7.00 pm with the Shyam aarti. The Kedarnath temple opens for darshan for the general public around 6 am.\\r\\n\\r\\nVisitors can touch idle and perform Abhishek with Ghee before 3 p.m. After 5 p.m., no one can approach Idle, but they can get Darshan from a distance. The temple at Kedarnath opens only six months of the year when the sun enters the zodiac sign of Aries and Scorpio is in full-blown eclipse.', '646710fdbe0dc.jpeg', '2024-04-23 18:38:11', NULL),
(18, 'Mata Vaishno Devi Temple', 'Katra-Jammu & Kashmir', 'The second-most visited Hindu pilgrimage destination in India, Mata Vaishno Devi Cave Temple is situated in the Trikuta Hills in Katra, Jammu & Kashmir. Hindu devotees from all over the world visit this famed religious site where the Mother Goddess or Mata Vaishno Devi is said to fulfill their wishes. This religious place is considered the most important Shaktipeeth as it is believed, here the skull of the Goddess Sati fell.\r\n\r\nAt Mata Vaishno Devi Cave, the goddess is in the form of a five and a half feet tall rock which has three heads or the Pindies. On Mata Vaishno Devi pilgrimage, devotees make traditional offerings to Mata of chunri (a red coloured drape), sarees, dry fruits, silver or gold ornaments, cholas, flowers etc.\r\nMata Vaishno Devi Shrine Board was formedu in 1986 and ever since this most popular religious site in Jammu started to attract a lot of Hindu pilgrims.\r\n\r\nThe holy cave of Mata Vaishno Devi is said to have been discovered by Pandit Sridhar, a Hindu priest. Goddess Vaishnavi appeared in the dream of the priest and instructed him on how to find here abode on Trikuta Hills. The priest following her instruction heads out for the journey after the dream and found the cave as instructed earlier. Mata Vaishno Devi appeared to him and blessed him with four sons. She also gave him the boon of being the custodian of the cave. Even today, Pandit Shridhar’s descendant abide by the commitment.', '64670bad37421.jpg', '2023-05-19 06:09:43', NULL);



CREATE TABLE `tbltourpackages` (
  `PackageId` int(11) NOT NULL,
  `PackageName` varchar(200) DEFAULT NULL,
  `PackageType` varchar(150) DEFAULT NULL,
  `PackageLocation` varchar(100) DEFAULT NULL,
  `PackagePrice` int(11) DEFAULT NULL,
  `PackageFetures` varchar(255) DEFAULT NULL,
  `PackageDetails` mediumtext DEFAULT NULL,
  `PackageImage` varchar(100) DEFAULT NULL,
  `Creationdate` timestamp NULL DEFAULT current_timestamp(),
  `UpdationDate` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;



INSERT INTO `tbltourpackages` (`PackageId`, `PackageName`, `PackageType`, `PackageLocation`, `PackagePrice`, `PackageFetures`, `PackageDetails`, `PackageImage`, `Creationdate`, `UpdationDate`) VALUES
(17, 'Kedarnath Town in Uttarakhand', 'Single', 'Uttarakhand', 8999, 'Free pickup and drop facility', 'Kedarnath is one of the most sacred pilgrimages of Lord Shiva situated in Rudraprayag district of Garhwal region in Uttarakhand. Kedarnath is one of the Char Dham in Uttarakhand and the most important dham among Panch kedar. Kedarnath is situated at an altitude of 3586 mts, in the lap of the majestic mountain peaks and near the head of river Mandakini, Kedarnath range stands one of the twelve Jyotirlingas of Lord Shiva.\\r\\n\\r\\nKedar meaning powerful is another name of Lord Shiva the protector and the destroyer. The beautiful ambiance around the temple looks like quite peace on heaven causes a beautiful place to do meditation.The main attractions here is the Shiva Temple, which is a popular Hindu shrine and pilgrimage, attracting devotees from all over the world. The travel and tourism scope here is strengthened by factors like natural beauty and religious zest.\\r\\n\\r\\nShiva is considered the embodiment of all passions - love, hatred, fear, death and mysticism which are expressed through his various forms. There are more than 200 shrines dedicated to Lord Shiva in the area itself, the most important one is Kedarnath.\\r\\nKedarnath Temple is the most revered shrine of Hindu deity Lord Shiva. The Mandir was built in 8th century A.D. by Adi Shankaracharya. It is adjacent to the site of an earlier temple built by the Pandavas. Kedarnath is one of India’s most famous temples (more than 1000 years old temple) dedicated to Lord Shiva.\\r\\n\\r\\nKedarnath Temple complex is being rehabilitated after 2013 Kedarnath floods. New facilities include helipads, helipad and new guest houses. Online facilities for Kedarnath booking are also there. Kedarnath Puja can be book online and no physical presence of devotees needed. Some pujas could be book on the internet or in person. The daily pooja rituals at the Kedarnath temple start early morning, around 4.00 am with Maha Abhishek and end at around 7.00 pm with the Shyam aarti. The Kedarnath temple opens for darshan for the general public around 6 am.\\r\\n\\r\\nVisitors can touch idle and perform Abhishek with Ghee before 3 p.m. After 5 p.m., no one can approach Idle, but they can get Darshan from a distance. The temple at Kedarnath opens only six months of the year when the sun enters the zodiac sign of Aries and Scorpio is in full-blown eclipse.', '646710fdbe0dc.jpeg', '2024-04-23 18:41:16', NULL),
(18, 'Taj Mahal-An immense mausoleum', 'Family Package', 'Agra', 5699, 'Free pickup and drop facility', 'The Taj Mahal is located on the right bank of the Yamuna River in a vast Mughal garden that encompasses nearly 17 hectares, in the Agra District in Uttar Pradesh. It was built by Mughal Emperor Shah Jahan in memory of his wife Mumtaz Mahal with construction starting in 1632 AD and completed in 1648 AD, with the mosque, the guest house and the main gateway on the south, the outer courtyard and its cloisters were added subsequently and completed in 1653 AD. The existence of several historical and Quaranic inscriptions in Arabic script have facilitated setting the chronology of Taj Mahal. For its construction, masons, stone-cutters, inlayers, carvers, painters, calligraphers, dome builders and other artisans were requisitioned from the whole of the empire and also from the Central Asia and Iran. Ustad-Ahmad Lahori was the main architect of the Taj Mahal.\r\n\r\nThe Taj Mahal is considered to be the greatest architectural achievement in the whole range of Indo-Islamic architecture. Its recognised architectonic beauty has a rhythmic combination of solids and voids, concave and convex and light shadow; such as arches and domes further increases the aesthetic aspect. The colour combination of lush green scape reddish pathway and blue sky over it show cases the monument in ever changing tints and moods. The relief work in marble and inlay with precious and semi precious stones make it a monument apart. \r\nThe four free-standing minarets at the corners of the platform added a hitherto unknown dimension to the Mughal architecture. The four minarets provide not only a kind of spatial reference to the monument but also give a three dimensional effect to the edifice.\r\n\r\nThe most impressive in the Taj Mahal complex next to the tomb, is the main gate which stands majestically in the centre of the southern wall of the forecourt. The gate is flanked on the north front by double arcade galleries. The garden in front of the galleries is subdivided into four quarters by two main walk-ways and each quarters in turn subdivided by the narrower cross-axial walkways, on the Timurid-Persian scheme of the walled in garden. The enclosure walls on the east and west have a pavilion at the centre.', '6466ff8b68299.jpg', '2023-05-19 04:57:39', '2024-04-23 18:17:51'),
(19, 'Darjeeling-Town in West Bengal', 'Couple', 'West Bengal', 6550, 'Free pickup and drop facility', 'The following day, we got up late, but it was still dark outside. An irritating faint knocking sound on the window did wake me. I reluctantly moved the curtains and what I saw outside made me rub my eyes. It’s snowing! The snowflakes were knocking against the glass panes. With uncontrollable excitement, we decided the venture to Chowrasta. Foggy weather conditions and low visibility forced most people to stay indoors, barring a few excited tourists like us from the plains who flocked the hills to witness the snowfall. The temperature was 3°C and, thankfully, was not windy. We did experience snowfall earlier, but it was a lifetime experience for kids – their first snowfall. I was awestruck to see that still there is a long queue out Kev’s for breakfast. Adverse weather did not allow us to stay out for long; we had to come back after spending a couple of hours. The rest of the day was lazing on the couch, watching online streaming and enjoying our favourite poison. We had Darjeeling offbeat locations travel plans the following days. But not sure about the feasibility in the present climatic conditions. The alarm goes off. What torture during holidays! The room is freezing outside the electric blanket. Saw the first glimpse of sunlight on the peak. An SMS flashing on the screen “Sir Ji, weather is clear. Be ready at 8.30”. I was about to ignore the alarm, then suddenly remembered our driver would honk in the next 90 minutes. Better wake up, make the kids ready and all set to a great day ahead. Around 9 am, after completing our banana pancake in breakfast, it is time we hit the road. Excited to think of the memories we are going to make today. Lepchajagat is 18 km from Darjeeling, at an altitude of 6959 feet. As the name suggests, the place was once predominantly a settlement by the Lepcha tribe. Today the tiny hamlet is significantly a reserve forest area filled with thick oak, firs and rhododendron trees. The offbeat forest is 45 minutes driving from Darjeeling.', '6467143468923.jpg', '2023-05-19 05:10:46', NULL),
(22, 'Ladakh, Jammu and Kashmir', 'Couple', 'Jammu and Kashmir', 8999, 'Free pickup and drop facility', 'Ladakh, union territory of India, located in the northern part of the Indian subcontinent in the vicinity of the Karakoram and westernmost Himalayan mountain ranges. It is bounded by Jammu and Kashmir union territory to the west and by Himachal Pradesh to the south; its northern and eastern borders are disputed with Pakistan and China, respectively. Ladakh was administered as part of Jammu and Kashmir state from 1947 until 2019, when it became a separate administrative unit. Area 22,836 square miles (59,146 square km). Pop. (2011) 274,289.\r\nGeologically complex and topographically immense, the Great Himalayas contain ranges with numerous peaks reaching elevations of 20,000 feet (6,100 metres) or higher, between which lie deeply entrenched remote valleys. Running parallel to the main Great Himalayas directly to the east is the Zaskar Range, which begins its flank from the main range at the Karnali River to the southeast of Ladakh. The zone was heavily glaciated during the Pleistocene Epoch, and remnant glaciers and snowfields are still present. The mountains constitute a climatic divide, representing a transition from the monsoon climate of the Indian subcontinent in neighbouring Jammu and Kashmir to the dry continental climate of Central Asia and Tibet.\r\nThe valley of the upper Indus River is a well-defined feature that follows the geologic strike (structural trend) westward from the Tibetan border to the point in the Pakistani sector of Kashmir where the river rounds the great mountainous mass of Nanga Parbat to run southward in deep gorges that cut across the strike. In its upper reaches the river is flanked by gravel terraces; each tributary builds an alluvial fan out into the main valley. The town of Leh stands on such a fan, 11,500 feet (3,500 metres) above sea level, with a climate characterized by an almost total lack of precipitation, by intense insolation (exposure to sunlight), and by great diurnal and annual ranges in temperature. Life depends on meltwater from the surrounding mountains, and vegetation is alpine (i.e., consists of species above the tree line), growing on thin soils.', '6467077b0c75d.jpg', '2023-05-19 05:22:03', NULL),
(24, 'Mysuru-City in Karnataka', 'Family Package', 'Karnataka', 7699, 'Free pickup and drop facility', 'Mysuru, also called Mysore, city, south-central Karnataka state, southern India. It lies northwest of Chamundi Hill and midway between the Kaveri (Cauvery) and Kabani (Kabbani) rivers on the undulating Deccan plateau at an elevation of 2,525 feet (770 metres). The land surrounding the city is characterized by rain-filled shallow depressions (tanks).\r\n\r\nThe site was mentioned in the epic Mahabharata as Mahishmati (Mahismati). Mysore was known as Purigere in the Mauryan era (3rd century BCE) and later became Mahishapura. It was the administrative capital of the princely state of Mysore from 1799 to 1831 and long was the second most-populous city (after Bengaluru [Bangalore]) of Karnataka state, until being surpassed by Hubballi-Dharwad in the second half of the 20th century. Its urban agglomeration, however, is still the state’s second largest.\r\n\r\nMysuru is an important manufacturing and trading centre, and it has textile (cotton and silk), rice, and oil mills, sandalwood-oil and chemical factories, and tanneries. The suburb of Belagula, to the northwest, produces chrome dyes and chemical fertilizer. The city’s industries are powered by the hydroelectric station near Sivasamudram Island to the east. Mysuru’s cottage industries include cotton weaving, tobacco and coffee processing, and the making of bidis (cigarettes). The area is known for its artwork in ivory, metal, and wood, and the market near the railway station serves as a collection centre for local farm products. The city has an airport, lies at the junction of two northern railway lines, and is a major intersection on India’s principal western road system.\r\nAn ancient fort, rebuilt along European lines in the 18th century, stands in the centre of Mysuru. The fort area comprises Mysore Palace (1912) with its ivory and gold throne, Curzon Park, the Silver Jubilee Clock Tower (1927), Gandhi Square, and two statues of maharajas. To the west, near Gordon Park, are the former British residency (1805), the noted Oriental Library, university buildings, and public offices. Jaganmohan Palace and Lalitha Mahal are other notable buildings. The University of Mysore was founded in 1916; other educational facilities include Maharaja’s College, Maharani’s College for Women, and affiliated colleges of medicine, law, engineering, and teacher training. There are also several institutions for the advancement of Kannada culture.', '6467097f8c7b1.jpg', '2023-05-19 05:30:39', NULL),
(27, 'Mata Vaishno Devi Temple', 'Family Package', 'Katra-Jammu & Kashmir', 8599, 'Free pickup and drop facility', 'The second-most visited Hindu pilgrimage destination in India, Mata Vaishno Devi Cave Temple is situated in the Trikuta Hills in Katra, Jammu & Kashmir. Hindu devotees from all over the world visit this famed religious site where the Mother Goddess or Mata Vaishno Devi is said to fulfill their wishes. This religious place is considered the most important Shaktipeeth as it is believed, here the skull of the Goddess Sati fell.\r\n\r\nAt Mata Vaishno Devi Cave, the goddess is in the form of a five and a half feet tall rock which has three heads or the Pindies. On Mata Vaishno Devi pilgrimage, devotees make traditional offerings to Mata of chunri (a red coloured drape), sarees, dry fruits, silver or gold ornaments, cholas, flowers etc.\r\nMata Vaishno Devi Shrine Board was formedu in 1986 and ever since this most popular religious site in Jammu started to attract a lot of Hindu pilgrims.\r\n\r\nThe holy cave of Mata Vaishno Devi is said to have been discovered by Pandit Sridhar, a Hindu priest. Goddess Vaishnavi appeared in the dream of the priest and instructed him on how to find here abode on Trikuta Hills. The priest following her instruction heads out for the journey after the dream and found the cave as instructed earlier. Mata Vaishno Devi appeared to him and blessed him with four sons. She also gave him the boon of being the custodian of the cave. Even today, Pandit Shridhar’s descendant abide by the commitment.', '64670bad37421.jpg', '2023-05-19 05:39:57', NULL);



CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` enum('user','admin') NOT NULL DEFAULT 'user',
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `RegDate` timestamp NULL DEFAULT current_timestamp(),
  `UpdationDate` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



INSERT INTO `users` (`id`, `name`, `email`, `password`, `role`, `status`, `RegDate`, `UpdationDate`) VALUES
(12, 'pratik', 'pratik@gmail.com', 'Pratik12', 'user', 'active', '2024-04-22 19:45:27', NULL),
(14, 'Harsh', 'harsh@gmail.com', 'harsh07', 'user', 'active', '2024-04-23 07:37:42', NULL);


ALTER TABLE `booking`
  ADD PRIMARY KEY (`BookingId`);


ALTER TABLE `packageoffer`
  ADD PRIMARY KEY (`OfferId`);


ALTER TABLE `tbldestination`
  ADD PRIMARY KEY (`DestinationId`);


ALTER TABLE `tbltourpackages`
  ADD PRIMARY KEY (`PackageId`);


ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `booking`
  MODIFY `BookingId` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;


ALTER TABLE `packageoffer`
  MODIFY `OfferId` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;


ALTER TABLE `tbldestination`
  MODIFY `DestinationId` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;


ALTER TABLE `tbltourpackages`
  MODIFY `PackageId` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=28;


ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;
COMMIT;

